//! XHTTP stream-one over HTTP/2, isolated from the HTTP/1 transport owner.
//!
//! Source: transport/internet/splithttp/{client,config,hub,dialer}.go. A single
//! request body is the uplink and its response body is the downlink. Despite
//! application/grpc camouflage, DATA is raw application bytes: no gRPC message
//! envelopes or grpc-status trailers exist. Both directions may half-close.
//!
//! Integration requires `pub mod http2;` in the parent xhttp module. Existing
//! Config request/response/metadata/padding helpers are reused, translating only
//! their HTTP framing. The client requires explicit stream-one; packet-up,
//! stream-up, auto-mode selection, Xmux policy, and HTTP/3 remain outer work.
//! Supplied TLS/REALITY streams must have actually negotiated h2. This module
//! cannot inspect TLS metadata once it has been erased into BoxStream.

use std::{
    collections::HashSet,
    future::Future,
    io,
    pin::Pin,
    sync::Arc,
    task::{Context, Poll, ready},
    time::Duration,
};

use bytes::{Buf, Bytes, BytesMut};
use h2::{RecvStream, SendStream, client::ResponseFuture};
use http::{
    HeaderMap, HeaderName, HeaderValue, Method, Request, Response, StatusCode, Uri, Version,
};
use tokio::{
    io::{AsyncRead, AsyncWrite, ReadBuf},
    sync::mpsc,
    task::JoinHandle,
};

use super::{Config, Connector, Head, Mode};
use crate::transport::BoxStream;

const WRITE_CHUNK: usize = 16 * 1024;
const ACCEPT_QUEUE: usize = 64;
// Larger than one stream window, while remaining a fixed connection memory
// bound: one unread tunnel must not immediately consume every stream's budget.
const CONNECTION_WINDOW: u32 = 1024 * 1024;
const HANDSHAKE_TIMEOUT: Duration = Duration::from_secs(30);

fn invalid(error: impl std::fmt::Display) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
}

fn h2_error(error: h2::Error) -> io::Error {
    let kind = if let Some(error) = error.get_io() {
        error.kind()
    } else if error.reason() == Some(h2::Reason::CANCEL) {
        io::ErrorKind::Interrupted
    } else {
        io::ErrorKind::ConnectionAborted
    };
    io::Error::new(kind, error)
}

fn validate_client(config: &Config) -> io::Result<()> {
    if config.mode() != Mode::StreamOne {
        return Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "HTTP/2 XHTTP client implements explicit stream-one only",
        ));
    }
    let authority: http::uri::Authority = config.host.parse().map_err(invalid)?;
    if authority.host().is_empty() || config.host.contains('@') {
        return Err(invalid("HTTP/2 XHTTP client requires a valid authority"));
    }
    Ok(())
}

/// Strip only HTTP/1 hop-by-hop fields and framing. All XHTTP camouflage,
/// cookies, padding, and CORS values are generated by the shared parent helpers.
fn h2_headers(headers: &[httparse::Header<'_>], maximum: usize) -> io::Result<HeaderMap> {
    let mut connection_tokens = HashSet::new();
    for header in headers {
        if header.name.eq_ignore_ascii_case("connection") {
            for token in std::str::from_utf8(header.value)
                .map_err(invalid)?
                .split(',')
            {
                connection_tokens.insert(token.trim().to_ascii_lowercase());
            }
        }
    }
    let mut result = HeaderMap::new();
    let mut length = 0usize;
    for header in headers {
        let name = header.name.to_ascii_lowercase();
        if matches!(
            name.as_str(),
            "connection"
                | "keep-alive"
                | "proxy-connection"
                | "transfer-encoding"
                | "upgrade"
                | "host"
                | "content-length"
        ) || connection_tokens.contains(&name)
        {
            continue;
        }
        if name == "te" && !header.value.eq_ignore_ascii_case(b"trailers") {
            continue;
        }
        length = length.saturating_add(name.len() + header.value.len() + 32);
        if length > maximum {
            return Err(invalid("XHTTP HTTP/2 header list exceeds configured limit"));
        }
        result.append(
            HeaderName::from_bytes(name.as_bytes()).map_err(invalid)?,
            HeaderValue::from_bytes(header.value).map_err(invalid)?,
        );
    }
    Ok(result)
}

fn header_slots(wire: &[u8], maximum: usize) -> io::Result<usize> {
    if wire.len() > maximum {
        return Err(invalid(
            "XHTTP HTTP header template exceeds configured limit",
        ));
    }
    // Every line needs at least CRLF, so this remains bounded by the byte limit.
    let count = wire.windows(2).filter(|bytes| *bytes == b"\r\n").count();
    Ok(count)
}

fn request(config: &Config) -> io::Result<Request<()>> {
    let wire = config.stream_request("")?;
    let mut slots = vec![httparse::EMPTY_HEADER; header_slots(&wire, config.max_header)?];
    let mut parsed = httparse::Request::new(&mut slots);
    if parsed.parse(&wire).map_err(invalid)? != httparse::Status::Complete(wire.len()) {
        return Err(invalid("incomplete XHTTP request header template"));
    }
    let uri = Uri::builder()
        .scheme(config.scheme.as_str())
        .authority(config.host.as_str())
        .path_and_query(
            parsed
                .path
                .ok_or_else(|| invalid("missing XHTTP request path"))?,
        )
        .build()
        .map_err(invalid)?;
    let mut request = Request::builder()
        .method(
            Method::from_bytes(
                parsed
                    .method
                    .ok_or_else(|| invalid("missing XHTTP method"))?
                    .as_bytes(),
            )
            .map_err(invalid)?,
        )
        .version(Version::HTTP_2)
        .uri(uri)
        .body(())
        .map_err(invalid)?;
    *request.headers_mut() = h2_headers(parsed.headers, config.max_header)?;
    Ok(request)
}

fn response(
    config: &Config,
    request: &Head,
    status: u16,
    streaming: bool,
) -> io::Result<Response<()>> {
    let wire = config.response(request, status, streaming);
    let mut slots = vec![httparse::EMPTY_HEADER; header_slots(&wire, config.max_header)?];
    let mut parsed = httparse::Response::new(&mut slots);
    if parsed.parse(&wire).map_err(invalid)? != httparse::Status::Complete(wire.len()) {
        return Err(invalid("incomplete XHTTP response header template"));
    }
    let mut response = Response::builder()
        .status(status)
        .version(Version::HTTP_2)
        .body(())
        .map_err(invalid)?;
    *response.headers_mut() = h2_headers(parsed.headers, config.max_header)?;
    Ok(response)
}

fn request_head(request: &Request<RecvStream>, maximum: usize) -> io::Result<Head> {
    let target = request
        .uri()
        .path_and_query()
        .map(ToString::to_string)
        .unwrap_or_else(|| "/".into());
    let mut length = target.len() + request.method().as_str().len();
    let mut headers = Vec::new();
    for (name, value) in request.headers() {
        length = length.saturating_add(name.as_str().len() + value.as_bytes().len() + 32);
        if length > maximum {
            return Err(invalid(
                "XHTTP HTTP/2 request headers exceed configured limit",
            ));
        }
        headers.push((
            name.to_string(),
            std::str::from_utf8(value.as_bytes())
                .map_err(invalid)?
                .to_owned(),
        ));
    }
    // :authority is the canonical HTTP/2 host; do not let a second Host field
    // override it. A missing authority retains any ordinary Host fallback.
    if let Some(authority) = request.uri().authority() {
        headers.retain(|(name, _)| !name.eq_ignore_ascii_case("host"));
        headers.push(("Host".into(), authority.to_string()));
    }
    Ok(Head {
        method: request.method().to_string(),
        target,
        status: 0,
        headers,
    })
}

struct Driver(JoinHandle<()>);
impl Drop for Driver {
    fn drop(&mut self) {
        self.0.abort();
    }
}

/// One reusable HTTP/2 connection. This is connection reuse, not Xray's Xmux
/// balancing, lifetime, request-count, or retry policy.
#[derive(Clone)]
pub struct Client {
    sender: h2::client::SendRequest<Bytes>,
    config: Arc<Config>,
    driver: Arc<Driver>,
}

impl Client {
    pub async fn handshake(io: BoxStream, config: Config) -> io::Result<Self> {
        validate_client(&config)?;
        let mut builder = h2::client::Builder::new();
        builder
            .max_header_list_size(config.max_header as u32)
            .initial_connection_window_size(CONNECTION_WINDOW)
            .max_send_buffer_size(WRITE_CHUNK * 2);
        let (sender, connection) = tokio::time::timeout(HANDSHAKE_TIMEOUT, builder.handshake(io))
            .await
            .map_err(|_| {
                io::Error::new(
                    io::ErrorKind::TimedOut,
                    "XHTTP HTTP/2 client handshake timed out",
                )
            })?
            .map_err(h2_error)?;
        let driver = Arc::new(Driver(tokio::spawn(async move {
            if let Err(error) = connection.await {
                tracing::debug!(%error, "XHTTP HTTP/2 client connection ended");
            }
        })));
        Ok(Self {
            sender,
            config: Arc::new(config),
            driver,
        })
    }

    /// Return after queuing request headers, before receiving response headers.
    /// The peer is allowed to wait for application DATA before responding.
    pub async fn open(&self) -> io::Result<Tunnel> {
        let mut sender = self.sender.clone().ready().await.map_err(h2_error)?;
        let (response, send) = sender
            .send_request(request(&self.config)?, false)
            .map_err(h2_error)?;
        Ok(Tunnel::new(
            Role::Client,
            send,
            None,
            Some(response),
            Some(self.driver.clone()),
        ))
    }
}

/// Fresh physical connection convenience adapter, matching the parent Connector
/// shape. The returned Tunnel owns the driver's lifetime after Client is dropped.
pub async fn connect(config: Config, connector: Connector) -> io::Result<BoxStream> {
    validate_client(&config)?;
    let client = Client::handshake(connector().await?, config).await?;
    Ok(client.open().await?.boxed())
}

/// Drives one physical HTTP/2 connection and yields every accepted logical
/// stream-one tunnel. A bounded queue never stalls the underlying H2 driver.
pub struct Server {
    incoming: mpsc::Receiver<io::Result<Tunnel>>,
    driver: Arc<Driver>,
}

impl Server {
    pub async fn handshake(io: BoxStream, config: Config) -> io::Result<Self> {
        if !config.mode.allows_stream_one() {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "XHTTP HTTP/2 server implements stream-one only",
            ));
        }
        let mut builder = h2::server::Builder::new();
        builder
            .max_header_list_size(config.max_header as u32)
            .initial_connection_window_size(CONNECTION_WINDOW)
            .max_concurrent_streams(ACCEPT_QUEUE as u32)
            .max_send_buffer_size(WRITE_CHUNK * 2);
        let mut connection =
            tokio::time::timeout(HANDSHAKE_TIMEOUT, builder.handshake::<_, Bytes>(io))
                .await
                .map_err(|_| {
                    io::Error::new(
                        io::ErrorKind::TimedOut,
                        "XHTTP HTTP/2 server handshake timed out",
                    )
                })?
                .map_err(h2_error)?;
        let (sender, incoming) = mpsc::channel(ACCEPT_QUEUE);
        let driver = Arc::new(Driver(tokio::spawn(async move {
            let mut closing = false;
            loop {
                let next = tokio::select! {
                    _ = sender.closed(), if !closing => {
                        closing = true;
                        connection.graceful_shutdown();
                        continue;
                    }
                    next = connection.accept() => next,
                };
                let Some(next) = next else {
                    break;
                };
                let (request, response) = match next {
                    Ok(next) => next,
                    Err(error) => {
                        let _ = sender.try_send(Err(h2_error(error)));
                        break;
                    }
                };
                match accept_request(request, response, &config) {
                    Ok(Some(tunnel)) => {
                        // A failed try_send drops and cancels only the excess
                        // stream; it cannot suspend other streams' I/O.
                        let _ = sender.try_send(Ok(tunnel));
                    }
                    Ok(None) => {}
                    Err(error) => tracing::debug!(%error, "XHTTP HTTP/2 request rejected"),
                }
            }
        })));
        Ok(Self { incoming, driver })
    }

    pub async fn accept(&mut self) -> io::Result<Option<Tunnel>> {
        match self.incoming.recv().await {
            Some(Ok(mut tunnel)) => {
                tunnel.driver = Some(self.driver.clone());
                Ok(Some(tunnel))
            }
            Some(Err(error)) => Err(error),
            None => Ok(None),
        }
    }
}

fn accept_request(
    request: Request<RecvStream>,
    mut responder: h2::server::SendResponse<Bytes>,
    config: &Config,
) -> io::Result<Option<Tunnel>> {
    let head = request_head(&request, config.max_header)?;
    let metadata = config.metadata(&head);
    let status = if (!config.host.is_empty() && !super::valid_host(head.get("Host"), &config.host))
        || metadata.is_err()
    {
        404
    } else if head.method == "OPTIONS" {
        200
    } else if !config.valid_padding(&head) {
        400
    } else if metadata
        .as_ref()
        .is_ok_and(|(session, _)| !session.is_empty())
    {
        400
    } else {
        200
    };
    if status != 200 || head.method == "OPTIONS" {
        responder
            .send_response(response(config, &head, status, false)?, true)
            .map_err(h2_error)?;
        return Ok(None);
    }
    let send = responder
        .send_response(response(config, &head, 200, true)?, false)
        .map_err(h2_error)?;
    Ok(Some(Tunnel::new(
        Role::Server,
        send,
        Some(request.into_body()),
        None,
        None,
    )))
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum Role {
    Client,
    Server,
}

/// Direct raw HTTP/2 body adapter. At most one received DATA frame is retained;
/// receive capacity is released only as bytes are copied to the application.
/// Writes reserve capacity before copying at most 16 KiB into the H2 sender.
pub struct Tunnel {
    role: Role,
    send: SendStream<Bytes>,
    recv: Option<RecvStream>,
    response: Option<ResponseFuture>,
    received: Bytes,
    read_closed: bool,
    write_closed: bool,
    data_ended: bool,
    terminal_error: Option<(io::ErrorKind, String)>,
    driver: Option<Arc<Driver>>,
}

impl Tunnel {
    fn new(
        role: Role,
        send: SendStream<Bytes>,
        recv: Option<RecvStream>,
        response: Option<ResponseFuture>,
        driver: Option<Arc<Driver>>,
    ) -> Self {
        Self {
            role,
            send,
            recv,
            response,
            received: Bytes::new(),
            read_closed: false,
            write_closed: false,
            data_ended: false,
            terminal_error: None,
            driver,
        }
    }

    pub fn boxed(self) -> BoxStream {
        Box::new(self)
    }

    fn poll_read_inner(
        &mut self,
        cx: &mut Context<'_>,
        buf: &mut ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        if let Some((kind, message)) = &self.terminal_error {
            return Poll::Ready(Err(io::Error::new(*kind, message.clone())));
        }
        if self.read_closed || buf.remaining() == 0 {
            return Poll::Ready(Ok(()));
        }
        if let Some(response) = &mut self.response {
            let response = ready!(Pin::new(response).poll(cx)).map_err(h2_error)?;
            self.response = None;
            if response.status() != StatusCode::OK {
                return Poll::Ready(Err(invalid(format!(
                    "XHTTP HTTP/2 response status {}",
                    response.status()
                ))));
            }
            if response
                .headers()
                .get("content-encoding")
                .is_some_and(|value| !value.as_bytes().eq_ignore_ascii_case(b"identity"))
            {
                return Poll::Ready(Err(io::Error::new(
                    io::ErrorKind::Unsupported,
                    "compressed XHTTP response bodies are not implemented",
                )));
            }
            self.recv = Some(response.into_body());
        }
        for _ in 0..64 {
            let recv = self
                .recv
                .as_mut()
                .expect("response installs receive stream");
            if !self.received.is_empty() {
                let length = self.received.len().min(buf.remaining());
                buf.put_slice(&self.received[..length]);
                self.received.advance(length);
                recv.flow_control()
                    .release_capacity(length)
                    .map_err(h2_error)?;
                return Poll::Ready(Ok(()));
            }
            if !self.data_ended {
                match ready!(recv.poll_data(cx)) {
                    Some(Ok(bytes)) => {
                        self.received = bytes;
                        continue;
                    }
                    Some(Err(error)) => return Poll::Ready(Err(h2_error(error))),
                    None => self.data_ended = true,
                }
            }
            // XHTTP is ordinary HTTP: trailers may exist but carry no mandatory
            // gRPC status. Polling them still surfaces an H2 failure.
            let _ = ready!(recv.poll_trailers(cx)).map_err(h2_error)?;
            self.read_closed = true;
            return Poll::Ready(Ok(()));
        }
        cx.waker().wake_by_ref();
        Poll::Pending
    }

    fn poll_capacity(&mut self, cx: &mut Context<'_>, desired: usize) -> Poll<io::Result<usize>> {
        if self.write_closed {
            return Poll::Ready(Err(io::Error::new(
                io::ErrorKind::BrokenPipe,
                "XHTTP HTTP/2 write side closed",
            )));
        }
        if let Poll::Ready(reset) = self.send.poll_reset(cx) {
            return Poll::Ready(Err(match reset {
                Ok(reason) => h2_error(reason.into()),
                Err(error) => h2_error(error),
            }));
        }
        if desired == 0 {
            return Poll::Ready(Ok(0));
        }
        self.send.reserve_capacity(desired.min(WRITE_CHUNK));
        if self.send.capacity() > 0 {
            return Poll::Ready(Ok(self.send.capacity().min(desired).min(WRITE_CHUNK)));
        }
        match ready!(self.send.poll_capacity(cx)) {
            Some(Ok(capacity)) if capacity > 0 => {
                Poll::Ready(Ok(capacity.min(desired).min(WRITE_CHUNK)))
            }
            Some(Ok(_)) => {
                cx.waker().wake_by_ref();
                Poll::Pending
            }
            Some(Err(error)) => Poll::Ready(Err(h2_error(error))),
            None => Poll::Ready(Err(io::Error::new(
                io::ErrorKind::BrokenPipe,
                "XHTTP HTTP/2 stream closed",
            ))),
        }
    }
}

impl AsyncRead for Tunnel {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        let result = self.poll_read_inner(cx, buf);
        if let Poll::Ready(Err(error)) = &result {
            self.terminal_error = Some((error.kind(), error.to_string()));
            self.send.send_reset(h2::Reason::CANCEL);
        }
        result
    }
}

impl AsyncWrite for Tunnel {
    fn poll_write(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        bytes: &[u8],
    ) -> Poll<io::Result<usize>> {
        let length = ready!(self.poll_capacity(cx, bytes.len()))?;
        if length > 0 {
            self.send
                .send_data(Bytes::copy_from_slice(&bytes[..length]), false)
                .map_err(h2_error)?;
        }
        Poll::Ready(Ok(length))
    }
    fn poll_write_vectored(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buffers: &[io::IoSlice<'_>],
    ) -> Poll<io::Result<usize>> {
        let desired = buffers
            .iter()
            .fold(0usize, |size, buffer| size.saturating_add(buffer.len()))
            .min(WRITE_CHUNK);
        let capacity = ready!(self.poll_capacity(cx, desired))?;
        let mut bytes = BytesMut::with_capacity(capacity);
        for buffer in buffers {
            let length = buffer.len().min(capacity - bytes.len());
            bytes.extend_from_slice(&buffer[..length]);
            if bytes.len() == capacity {
                break;
            }
        }
        let length = bytes.len();
        if length > 0 {
            self.send
                .send_data(bytes.freeze(), false)
                .map_err(h2_error)?;
        }
        Poll::Ready(Ok(length))
    }
    fn is_write_vectored(&self) -> bool {
        true
    }
    fn poll_flush(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        if self.write_closed {
            return Poll::Ready(Ok(()));
        }
        self.poll_capacity(cx, 0).map_ok(|_| ())
    }
    fn poll_shutdown(mut self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        if self.write_closed {
            return Poll::Ready(Ok(()));
        }
        self.send.send_data(Bytes::new(), true).map_err(h2_error)?;
        self.write_closed = true;
        Poll::Ready(Ok(()))
    }
}

impl Drop for Tunnel {
    fn drop(&mut self) {
        if !self.write_closed || (self.role == Role::Client && !self.read_closed) {
            self.send.send_reset(h2::Reason::CANCEL);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    fn config() -> Config {
        Config::from_json(&json!({"mode":"stream-one","path":"/xh","xPaddingBytes":100}))
            .unwrap()
            .with_authority("example.test", false)
            .unwrap()
    }

    async fn bounded<T>(future: impl Future<Output = T>) -> T {
        tokio::time::timeout(Duration::from_secs(8), future)
            .await
            .expect("XHTTP H2 test timed out")
    }

    async fn pair_with(client_config: Config, server_config: Config) -> (Client, Server) {
        let (a, b) = tokio::io::duplex(4096);
        let (client, server) = tokio::join!(
            Client::handshake(Box::new(a), client_config),
            Server::handshake(Box::new(b), server_config),
        );
        (client.unwrap(), server.unwrap())
    }

    async fn pair() -> (Client, Server) {
        pair_with(config(), config()).await
    }

    struct RawPeer {
        _client: Client,
        tunnel: Tunnel,
        request: Request<RecvStream>,
        response: h2::server::SendResponse<Bytes>,
        _driver: Driver,
    }

    async fn raw_peer(window: u32) -> RawPeer {
        let (a, b) = tokio::io::duplex(4096);
        let (tx, rx) = tokio::sync::oneshot::channel();
        let driver = Driver(tokio::spawn(async move {
            let mut builder = h2::server::Builder::new();
            builder.initial_window_size(window);
            let mut connection = builder
                .handshake::<_, Bytes>(Box::new(b) as BoxStream)
                .await
                .unwrap();
            assert!(tx.send(connection.accept().await.unwrap().unwrap()).is_ok());
            while connection.accept().await.is_some() {}
        }));
        let client = Client::handshake(Box::new(a), config()).await.unwrap();
        let tunnel = client.open().await.unwrap();
        let (request, response) = rx.await.unwrap();
        RawPeer {
            _client: client,
            tunnel,
            request,
            response,
            _driver: driver,
        }
    }

    fn response_headers() -> Response<()> {
        Response::builder()
            .status(200)
            .header("content-type", "text/event-stream")
            .body(())
            .unwrap()
    }

    #[test]
    fn request_reuses_source_camouflage_without_http1_framing() {
        let request = request(&config()).unwrap();
        assert_eq!(request.version(), Version::HTTP_2);
        assert_eq!(request.method(), Method::POST);
        assert_eq!(request.uri().scheme_str(), Some("http"));
        assert_eq!(request.uri().authority().unwrap().as_str(), "example.test");
        assert_eq!(request.uri().path(), "/xh/");
        assert_eq!(request.headers()["content-type"], "application/grpc");
        assert_eq!(request.headers()["accept-encoding"], "identity");
        assert_eq!(
            request.headers()["referer"],
            format!("http://example.test/xh/?x_padding={}", "X".repeat(100))
        );
        for name in ["host", "connection", "transfer-encoding", "content-length"] {
            assert!(!request.headers().contains_key(name));
        }
    }

    #[test]
    fn h2_headers_strip_connection_nominated_fields_and_invalid_te() {
        let input = [
            httparse::Header {
                name: "Connection",
                value: b"close, x-hop",
            },
            httparse::Header {
                name: "X-Hop",
                value: b"must not leak",
            },
            httparse::Header {
                name: "Keep-Alive",
                value: b"timeout=5",
            },
            httparse::Header {
                name: "Proxy-Connection",
                value: b"keep-alive",
            },
            httparse::Header {
                name: "TE",
                value: b"gzip",
            },
            httparse::Header {
                name: "X-Custom",
                value: b"keep",
            },
        ];
        let headers = h2_headers(&input, 8192).unwrap();
        assert_eq!(headers.len(), 1);
        assert_eq!(headers["x-custom"], "keep");
        let headers = h2_headers(
            &[httparse::Header {
                name: "TE",
                value: b"trailers",
            }],
            8192,
        )
        .unwrap();
        assert_eq!(headers["te"], "trailers");
        assert!(h2_headers(&input, 1).is_err());
    }

    #[test]
    fn response_reuses_sse_padding_cors_and_cookie_credential_rules() {
        let c = Config::from_json(&json!({"mode":"stream-one","path":"/xh","xPaddingBytes":100,"xPaddingObfsMode":true,"xPaddingPlacement":"cookie","xPaddingKey":"pad"})).unwrap();
        let head = Head {
            method: "POST".into(),
            target: "/xh/".into(),
            status: 0,
            headers: vec![("Origin".into(), "https://site.test".into())],
        };
        let response = response(&c, &head, 200, true).unwrap();
        assert_eq!(response.headers()["content-type"], "text/event-stream");
        assert_eq!(response.headers()["x-accel-buffering"], "no");
        assert_eq!(response.headers()["cache-control"], "no-store");
        assert_eq!(
            response.headers()["access-control-allow-origin"],
            "https://site.test"
        );
        assert_eq!(
            response.headers()["access-control-allow-credentials"],
            "true"
        );
        assert_eq!(
            response.headers()["set-cookie"],
            format!("pad={}", "X".repeat(100))
        );
        assert!(!response.headers().contains_key("transfer-encoding"));
    }

    #[test]
    fn no_grpc_and_no_sse_headers_do_not_change_body_semantics() {
        let c = Config::from_json(&json!({"mode":"stream-one","noGRPCHeader":true,"noSSEHeader":true,"xPaddingBytes":100})).unwrap().with_authority("example.test", true).unwrap();
        let req = request(&c).unwrap();
        assert_eq!(req.uri().scheme_str(), Some("https"));
        assert!(!req.headers().contains_key("content-type"));
        let head = Head {
            method: "POST".into(),
            target: "/".into(),
            status: 0,
            headers: Vec::new(),
        };
        assert!(
            !response(&c, &head, 200, true)
                .unwrap()
                .headers()
                .contains_key("content-type")
        );
    }

    #[test]
    fn client_rejects_auto_split_modes_and_missing_authority() {
        for mode in ["auto", "packet-up", "stream-up"] {
            let c = Config::from_json(&json!({"mode":mode}))
                .unwrap()
                .with_authority("example.test", false)
                .unwrap();
            assert_eq!(
                validate_client(&c).unwrap_err().kind(),
                io::ErrorKind::Unsupported
            );
        }
        let c = Config::from_json(&json!({"mode":"stream-one"})).unwrap();
        assert!(validate_client(&c).is_err());
    }

    #[tokio::test]
    async fn raw_data_wire_has_no_grpc_envelope_and_waits_for_no_headers() {
        bounded(async {
            let mut peer = raw_peer(65_535).await;
            assert_eq!(peer.request.headers()["content-type"], "application/grpc");
            let payload = b"\0\xffunframed uplink";
            peer.tunnel.write_all(payload).await.unwrap();
            let mut incoming = peer.request.into_body();
            let bytes = incoming.data().await.unwrap().unwrap();
            assert_eq!(bytes.as_ref(), payload);
            incoming
                .flow_control()
                .release_capacity(bytes.len())
                .unwrap();
            // Initial DATA arrived while response HEADERS were still withheld.
            let mut send = peer
                .response
                .send_response(response_headers(), false)
                .unwrap();
            send.send_data(Bytes::from_static(b"unframed downlink"), true)
                .unwrap();
            peer.tunnel.shutdown().await.unwrap();
            let mut response = Vec::new();
            peer.tunnel.read_to_end(&mut response).await.unwrap();
            assert_eq!(response, b"unframed downlink");
        })
        .await;
    }

    #[tokio::test]
    async fn raw_bidirectional_round_trip_preserves_half_close_and_vectors() {
        bounded(async {
            let (client, mut server) = pair().await;
            let mut outbound = client.open().await.unwrap();
            let mut inbound = server.accept().await.unwrap().unwrap();
            assert_eq!(
                outbound
                    .write_vectored(&[io::IoSlice::new(b"hello"), io::IoSlice::new(b" world")])
                    .await
                    .unwrap(),
                11
            );
            outbound.shutdown().await.unwrap();
            let mut data = Vec::new();
            inbound.read_to_end(&mut data).await.unwrap();
            assert_eq!(data, b"hello world");
            inbound
                .write_all(b"still readable after request EOF")
                .await
                .unwrap();
            inbound.shutdown().await.unwrap();
            let mut reply = Vec::new();
            outbound.read_to_end(&mut reply).await.unwrap();
            assert_eq!(reply, b"still readable after request EOF");
            assert_eq!(
                outbound.write(b"closed").await.unwrap_err().kind(),
                io::ErrorKind::BrokenPipe
            );
        })
        .await;
    }

    #[tokio::test]
    async fn simultaneous_large_uplink_and_downlink_respect_flow_control() {
        bounded(async {
            let (client, mut server) = pair().await;
            let outbound = client.open().await.unwrap();
            let inbound = server.accept().await.unwrap().unwrap();
            let (mut client_read, mut client_write) = tokio::io::split(outbound);
            let (mut server_read, mut server_write) = tokio::io::split(inbound);
            let up: Vec<u8> = (0..1024 * 1024).map(|i| (i % 251) as u8).collect();
            let down: Vec<u8> = (0..1024 * 1024).map(|i| (i % 239) as u8).collect();
            tokio::join!(
                async {
                    client_write.write_all(&up).await.unwrap();
                    client_write.shutdown().await.unwrap();
                },
                async {
                    server_write.write_all(&down).await.unwrap();
                    server_write.shutdown().await.unwrap();
                },
                async {
                    let mut bytes = Vec::new();
                    server_read.read_to_end(&mut bytes).await.unwrap();
                    assert_eq!(bytes, up);
                },
                async {
                    let mut bytes = Vec::new();
                    client_read.read_to_end(&mut bytes).await.unwrap();
                    assert_eq!(bytes, down);
                }
            );
        })
        .await;
    }

    #[tokio::test]
    async fn all_padding_placements_reuse_the_same_metadata_contract() {
        bounded(async {
            for placement in ["query", "header", "cookie", "queryInHeader"] {
                let c = Config::from_json(&json!({"mode":"stream-one","path":"/pad","xPaddingBytes":100,"xPaddingObfsMode":true,"xPaddingPlacement":placement,"xPaddingHeader":"X-Pad","xPaddingKey":"padding"})).unwrap().with_authority("example.test", false).unwrap();
                let (client, mut server) = pair_with(c.clone(), c).await;
                let mut outbound = client.open().await.unwrap();
                let mut inbound = server.accept().await.unwrap().unwrap();
                outbound.write_all(placement.as_bytes()).await.unwrap(); outbound.shutdown().await.unwrap();
                let mut body = Vec::new(); inbound.read_to_end(&mut body).await.unwrap(); assert_eq!(body, placement.as_bytes());
                inbound.shutdown().await.unwrap(); assert_eq!(outbound.read(&mut [0u8; 1]).await.unwrap(), 0);
            }
        }).await;
    }

    #[tokio::test]
    async fn server_accepts_stream_one_under_auto_and_stream_up_modes() {
        bounded(async {
            for mode in ["auto", "stream-up"] {
                let server_config =
                    Config::from_json(&json!({"mode":mode,"path":"/xh","xPaddingBytes":100}))
                        .unwrap();
                let (client, mut server) = pair_with(config(), server_config).await;
                let mut outbound = client.open().await.unwrap();
                let mut inbound = server.accept().await.unwrap().unwrap();
                outbound.shutdown().await.unwrap();
                inbound.shutdown().await.unwrap();
                assert_eq!(outbound.read(&mut [0u8; 1]).await.unwrap(), 0);
            }
        })
        .await;
    }

    #[tokio::test]
    async fn bad_host_path_padding_and_split_session_get_http_rejections() {
        bounded(async {
            let (client, mut server) = pair().await;
            for (variant, expected) in [(0, 404), (1, 404), (2, 400), (3, 400)] {
                let mut request = request(&config()).unwrap();
                match variant {
                    0 => *request.uri_mut() = "http://wrong.test/xh/".parse().unwrap(),
                    1 => *request.uri_mut() = "http://example.test/wrong/".parse().unwrap(),
                    2 => {
                        request.headers_mut().remove("referer");
                    }
                    _ => *request.uri_mut() = "http://example.test/xh/session/".parse().unwrap(),
                }
                let mut sender = client.sender.clone().ready().await.unwrap();
                let (response, _) = sender.send_request(request, true).unwrap();
                assert_eq!(response.await.unwrap().status(), expected);
            }
            let mut valid = client.open().await.unwrap();
            let mut inbound = server.accept().await.unwrap().unwrap();
            valid.shutdown().await.unwrap();
            inbound.shutdown().await.unwrap();
            assert_eq!(valid.read(&mut [0u8; 1]).await.unwrap(), 0);
        })
        .await;
    }

    #[tokio::test]
    async fn preflight_uses_cors_response_without_creating_a_tunnel() {
        bounded(async {
            let (client, mut server) = pair().await;
            let mut preflight = request(&config()).unwrap();
            *preflight.method_mut() = Method::OPTIONS;
            preflight.headers_mut().remove("referer");
            preflight
                .headers_mut()
                .insert("origin", HeaderValue::from_static("https://origin.test"));
            preflight.headers_mut().insert(
                "access-control-request-method",
                HeaderValue::from_static("POST"),
            );
            preflight.headers_mut().insert(
                "access-control-request-headers",
                HeaderValue::from_static("x-test"),
            );
            let mut sender = client.sender.clone().ready().await.unwrap();
            let (response, _) = sender.send_request(preflight, true).unwrap();
            let response = response.await.unwrap();
            assert_eq!(response.status(), 200);
            assert_eq!(
                response.headers()["access-control-allow-origin"],
                "https://origin.test"
            );
            assert_eq!(response.headers()["access-control-allow-methods"], "POST");
            assert_eq!(response.headers()["access-control-allow-headers"], "x-test");
            assert!(
                tokio::time::timeout(Duration::from_millis(20), server.accept())
                    .await
                    .is_err()
            );
        })
        .await;
    }

    #[tokio::test]
    async fn dropping_one_tunnel_cancels_only_that_pooled_stream() {
        bounded(async {
            let (client, mut server) = pair().await;
            let canceled = client.open().await.unwrap();
            let mut first = server.accept().await.unwrap().unwrap();
            let mut survivor = client.clone().open().await.unwrap();
            let mut second = server.accept().await.unwrap().unwrap();
            drop(canceled);
            assert_eq!(
                first.read(&mut [0u8; 1]).await.unwrap_err().kind(),
                io::ErrorKind::Interrupted
            );
            survivor.write_all(b"survives").await.unwrap();
            survivor.shutdown().await.unwrap();
            let mut bytes = Vec::new();
            second.read_to_end(&mut bytes).await.unwrap();
            assert_eq!(bytes, b"survives");
            second.shutdown().await.unwrap();
            assert_eq!(survivor.read(&mut [0u8; 1]).await.unwrap(), 0);
        })
        .await;
    }

    #[tokio::test]
    async fn one_unread_stream_does_not_exhaust_the_connection_window() {
        bounded(async {
            let (client, mut server) = pair().await;
            let mut blocked = client.open().await.unwrap();
            let _unread = server.accept().await.unwrap().unwrap();
            blocked.write_all(&vec![1; 65_535]).await.unwrap();
            let mut second = client.open().await.unwrap();
            let mut reader = server.accept().await.unwrap().unwrap();
            second.write_all(b"independent").await.unwrap();
            second.shutdown().await.unwrap();
            let mut bytes = Vec::new();
            reader.read_to_end(&mut bytes).await.unwrap();
            assert_eq!(bytes, b"independent");
            reader.shutdown().await.unwrap();
            assert_eq!(second.read(&mut [0u8; 1]).await.unwrap(), 0);
        })
        .await;
    }

    #[tokio::test]
    async fn canceled_pending_write_does_not_accept_new_bytes() {
        bounded(async {
            let mut peer = raw_peer(16).await;
            let mut send = peer
                .response
                .send_response(response_headers(), false)
                .unwrap();
            assert!(
                tokio::time::timeout(Duration::from_millis(20), peer.tunnel.read(&mut [0u8; 1]))
                    .await
                    .is_err()
            );
            peer.tunnel.write_all(b"0123456789abcdef").await.unwrap();
            assert!(
                tokio::time::timeout(
                    Duration::from_millis(20),
                    peer.tunnel.write(b"not accepted")
                )
                .await
                .is_err()
            );
            let mut incoming = peer.request.into_body();
            let first = incoming.data().await.unwrap().unwrap();
            assert_eq!(first.as_ref(), b"0123456789abcdef");
            incoming
                .flow_control()
                .release_capacity(first.len())
                .unwrap();
            peer.tunnel.write_all(b"OK").await.unwrap();
            peer.tunnel.shutdown().await.unwrap();
            let mut tail = Vec::new();
            while let Some(data) = incoming.data().await {
                let data = data.unwrap();
                tail.extend_from_slice(&data);
                incoming
                    .flow_control()
                    .release_capacity(data.len())
                    .unwrap();
            }
            assert_eq!(tail, b"OK");
            send.send_data(Bytes::new(), true).unwrap();
            assert_eq!(peer.tunnel.read(&mut [0u8; 1]).await.unwrap(), 0);
        })
        .await;
    }

    #[tokio::test]
    async fn canceled_read_and_small_buffers_do_not_lose_data() {
        bounded(async {
            let mut peer = raw_peer(65_535).await;
            let mut send = peer
                .response
                .send_response(response_headers(), false)
                .unwrap();
            assert!(
                tokio::time::timeout(Duration::from_millis(20), peer.tunnel.read(&mut [0u8; 1]))
                    .await
                    .is_err()
            );
            send.send_data(Bytes::from_static(b"ABC"), false).unwrap();
            let mut bytes = Vec::new();
            for _ in 0..3 {
                let mut byte = [0u8; 1];
                peer.tunnel.read_exact(&mut byte).await.unwrap();
                bytes.push(byte[0]);
            }
            assert!(
                tokio::time::timeout(Duration::from_millis(20), peer.tunnel.read(&mut [0u8; 1]))
                    .await
                    .is_err()
            );
            send.send_data(Bytes::from_static(b"DEF"), true).unwrap();
            peer.tunnel.read_to_end(&mut bytes).await.unwrap();
            assert_eq!(bytes, b"ABCDEF");
        })
        .await;
    }

    #[tokio::test]
    async fn response_status_compression_and_connection_errors_are_not_eof() {
        bounded(async {
            for variant in 0..3 {
                let mut peer = raw_peer(65_535).await;
                if variant == 2 {
                    peer._driver.0.abort();
                    drop(peer.request);
                    drop(peer.response);
                } else {
                    let mut response = response_headers();
                    if variant == 0 {
                        *response.status_mut() = StatusCode::NOT_FOUND;
                    } else {
                        response
                            .headers_mut()
                            .insert("content-encoding", HeaderValue::from_static("gzip"));
                    }
                    peer.response.send_response(response, true).unwrap();
                }
                assert!(peer.tunnel.read(&mut [0u8; 1]).await.is_err());
                assert!(peer.tunnel.read(&mut [0u8; 1]).await.is_err());
            }
        })
        .await;
    }

    #[tokio::test]
    async fn ordinary_http_trailers_need_no_grpc_status() {
        bounded(async {
            let mut peer = raw_peer(65_535).await;
            let mut send = peer
                .response
                .send_response(response_headers(), false)
                .unwrap();
            send.send_data(Bytes::from_static(b"data"), false).unwrap();
            let mut trailers = HeaderMap::new();
            trailers.insert("x-finished", HeaderValue::from_static("yes"));
            send.send_trailers(trailers).unwrap();
            let mut data = Vec::new();
            peer.tunnel.read_to_end(&mut data).await.unwrap();
            assert_eq!(data, b"data");
        })
        .await;
    }

    #[tokio::test]
    async fn tunnels_keep_client_driver_alive_and_final_drop_releases_it() {
        bounded(async {
            let (client, mut server) = pair().await;
            let weak = Arc::downgrade(&client.driver);
            let mut outbound = client.open().await.unwrap();
            let mut inbound = server.accept().await.unwrap().unwrap();
            drop(client);
            assert!(weak.upgrade().is_some());
            outbound.write_all(b"owned").await.unwrap();
            outbound.shutdown().await.unwrap();
            let mut data = Vec::new();
            inbound.read_to_end(&mut data).await.unwrap();
            assert_eq!(data, b"owned");
            inbound.shutdown().await.unwrap();
            assert_eq!(outbound.read(&mut [0u8; 1]).await.unwrap(), 0);
            drop(outbound);
            assert!(weak.upgrade().is_none());
        })
        .await;
    }

    #[tokio::test]
    async fn connector_adapter_returns_a_live_tunnel_after_temporary_client_drop() {
        bounded(async {
            let (a, b) = tokio::io::duplex(4096);
            let io = Arc::new(tokio::sync::Mutex::new(Some(a)));
            let connector: Connector = Arc::new(move || {
                let io = io.clone();
                Box::pin(async move { Ok(Box::new(io.lock().await.take().unwrap()) as BoxStream) })
            });
            let (outbound, server) = tokio::join!(
                connect(config(), connector),
                Server::handshake(Box::new(b), config())
            );
            let mut outbound = outbound.unwrap();
            let mut server = server.unwrap();
            let mut inbound = server.accept().await.unwrap().unwrap();
            outbound.write_all(b"connector").await.unwrap();
            outbound.shutdown().await.unwrap();
            let mut bytes = Vec::new();
            inbound.read_to_end(&mut bytes).await.unwrap();
            assert_eq!(bytes, b"connector");
            inbound.shutdown().await.unwrap();
            assert_eq!(outbound.read(&mut [0u8; 1]).await.unwrap(), 0);
        })
        .await;
    }
}
